### ISSUE TITLE
ControlNet.__init__() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by jeffreyrobeson** [Kosinkadink/ComfyUI-Advanced-ControlNet#196]
ACN_ControlNet++LoaderSingle
ControlNet.__init__() got an unexpected keyword argument 'device'

**Comment by Kosinkadink** [comment]
Update your Advanced-ControlNet, issue has been fixed a couple weeks ago soon after a new ComfyUI version made old versions of Advanced-ControlNet incompatible.

**Comment by LMN007** [comment]
I download the newest version but the bug still exists. Here is the report:

# ComfyUI Error Report
## Error Details
- **Node ID:** 28
- **Node Type:** ACN_SparseCtrlLoaderAdvanced
- **Exception Type:** TypeError
- **Exception Message:** ControlNet.__init__() got an unexpected keyword argument 'device'
## Stack Trace
```
  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes_sparsectrl.py", line 45, in load_controlnet
    sparsectrl = load_sparsectrl(sparsectrl_path, timestep_keyframe=tk_optional, sparse_settings=sparse_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 795, in load_sparsectrl
    control = SparseCtrlAdvanced(control_model, timestep_keyframes=timestep_keyframe, sparse_settings=sparse_settings, global_average_pooling=global_average_pooling, load_device=load_device, manual_cast_dtype=manual_cast_dtype)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 315, in __init__
    super().__init__(control_model=control_model, timestep_keyframes=timestep_keyframes, global_average_pooling=global_average_pooling, device=device, load_device=load_device, manual_cast_dtype=manual_cast_dtype)

  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 25, in __init__
    super().__init__(control_model=control_model, global_average_pooling=global_average_pooling, compression_ratio=compression_ratio, latent_format=latent_format, device=device, load_device=load_device, manual_cast_dtype=manual_cast_dtype)

```
## System Information
- **ComfyUI Version:** unknown
- **Arguments:** ComfyUI\main.py --windows-standalone-build --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA RTX A5000 : native
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 21603359232
  - **Torch VRAM Total:** 3888119808
  - **Torch VRAM Free:** 1147738624

## Logs
```
2024-11-17T16:16:09.943464 - Windows2024-11-17T16:16:09.943464 - 
2024-11-17T16:16:09.943464 - ** Python version:2024-11-17T16:16:09.943464 -  2024-11-17T16:16:09.943464 - 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]2024-11-17T16:16:09.943464 - 
2024-11-17T16:16:09.943464 - ** Python executable:2024-11-17T16:16:09.943464 -  2024-11-17T16:16:09.943464 - D:\ComfyUI\ComfyUI_Max\python_embeded\python.exe2024-11-17T16:16:09.943464 - 
2024-11-17T16:16:09.943464 - ** ComfyUI Path:2024-11-17T16:16:09.943464 -  2024-11-17T16:16:09.943464 - D:\ComfyUI\ComfyUI_Max\ComfyUI2024-11-17T16:16:09.943464 - 
2024-11-17T16:16:09.943464 - ** Log path:2024-11-17T16:16:09.943464 -  2024-11-17T16:16:09.943464 - D:\ComfyUI\ComfyUI_Max\comfyui.log2024-11-17T16:16:09.943464 - 
2024-11-17T16:16:09.953996 - 
Prestartup times for custom nodes:2024-11-17T16:16:09.953996 - 
2024-11-17T16:16:09.953996 -    0.0 seconds:2024-11-17T16:16:09.953996 -  2024-11-17T16:16:09.953996 - D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\rgthree-comfy2024-11-17T16:16:09.953996 - 
2024-11-17T16:16:09.953996 -    0.0 seconds:2024-11-17T16:16:09.953996 -  2024-11-17T16:16:09.953996 - D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Easy-Use2024-11-17T16:16:09.953996 - 
2024-11-17T16:16:09.954996 -    2.5 seconds:2024-11-17T16:16:09.954996 -  2024-11-17T16:16:09.954996 - D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Manager2024-11-17T16:16:09.954996 - 
2024-11-17T16:16:09.954996 - 
2024-11-17T16:16:11.048420 - Total VRAM 24564 MB, total RAM 65241 MB
2024-11-17T16:16:11.048420 - pytorch version: 2.3.1+cu121
2024-11-17T16:16:11.843518 - xformers version: 0.0.27
2024-11-17T16:16:11.844518 - Set vram state to: NORMAL_VRAM
2024-11-17T16:16:11.844518 - Device: cuda:0 NVIDIA RTX A5000 : native
2024-11-17T16:16:12.007518 - Using xformers cross attention
2024-11-17T16:16:12.590351 - [Prompt Server] web root: D:\ComfyUI\ComfyUI_Max\ComfyUI\web
2024-11-17T16:16:13.289382 - Error:
[WinError 1] Incorrect function: 'D:\\ComfyUI\\ComfyUI_Max\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'D:\\ComfyUI\\ComfyUI_Max\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to D:\ComfyUI\ComfyUI_Max\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyLiterals\js
Target: D:\ComfyUI\ComfyUI_Max\ComfyUI\web\extensions\ComfyLiterals2024-11-17T16:16:13.291377 - 
2024-11-17T16:16:15.106447 - Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-11-17T16:16:15.106447 - NumExpr defaulting to 8 threads.
2024-11-17T16:16:15.584043 - [AnimateDiff] - [0;33mWARNING[0m - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
2024-11-17T16:16:15.586042 - [AnimateDiff] - [0;31mERROR[0m - No models available. Please download one and put it in models folder
2024-11-17T16:16:15.799047 - [36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2024-11-17T16:16:15.799047 - [36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-11-17T16:16:15.799047 - [36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-11-17T16:16:15.810560 - DWPose: Onnxruntime with acceleration providers detected2024-11-17T16:16:15.810560 - 
2024-11-17T16:16:16.983065 - sageattn not found, using sdpa
2024-11-17T16:16:16.989573 - sageattn not found, using sdpa
2024-11-17T16:16:16.990575 - sageattn not found, using sdpa
2024-11-17T16:16:17.029946 - [Crystools [0;32mINFO[0m] Crystools version: 1.19.0
2024-11-17T16:16:17.040456 - [Crystools [0;32mINFO[0m] CPU: 12th Gen Intel(R) Core(TM) i9-12900K - Arch: Arch unknown - OS: Windows 10
2024-11-17T16:16:17.048984 - [Crystools [0;32mINFO[0m] Pynvml (Nvidia) initialized.
2024-11-17T16:16:17.048984 - [Crystools [0;32mINFO[0m] GPU/s:
2024-11-17T16:16:17.054976 - [Crystools [0;32mINFO[0m] 0) NVIDIA RTX A5000
2024-11-17T16:16:17.054976 - [Crystools [0;32mINFO[0m] NVIDIA Driver: 552.86
2024-11-17T16:16:17.255635 - [34m[ComfyUI-Easy-Use] server: [0mv1.2.4 [92mLoaded[0m2024-11-17T16:16:17.255635 - 
2024-11-17T16:16:17.255635 - [34m[ComfyUI-Easy-Use] web root: [0mD:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 [92mLoaded[0m2024-11-17T16:16:17.255635 - 
2024-11-17T16:16:17.609603 - Total VRAM 24564 MB, total RAM 65241 MB
2024-11-17T16:16:17.610595 - pytorch version: 2.3.1+cu121
2024-11-17T16:16:17.610595 - xformers version: 0.0.27
2024-11-17T16:16:17.610595 - Set vram state to: NORMAL_VRAM
2024-11-17T16:16:17.610595 - Device: cuda:0 NVIDIA RTX A5000 : native
2024-11-17T16:16:17.625449 - [JNodes] - [0;32mINFO[0m - ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
2024-11-17T16:16:18.000466 - ### Loading: ComfyUI-Manager (V2.51.8)2024-11-17T16:16:18.000466 - 
2024-11-17T16:16:18.023614 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)2024-11-17T16:16:18.024615 - 
2024-11-17T16:16:18.045647 - [0m[1;34m[SD Prompt Reader] [36mNode version: 1.3.4[0m2024-11-17T16:16:18.045647 - 
2024-11-17T16:16:18.045647 - [0m[1;34m[SD Prompt Reader] [36mCore version: 1.3.5[0m2024-11-17T16:16:18.046647 - 
2024-11-17T16:16:18.051161 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-11-17T16:16:18.051161 - 
2024-11-17T16:16:18.070272 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-11-17T16:16:18.105397 - 
2024-11-17T16:16:18.123010 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-11-17T16:16:18.123010 - 
2024-11-17T16:16:18.154849 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-11-17T16:16:18.154849 - 
2024-11-17T16:16:18.188800 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-11-17T16:16:18.188800 - 
2024-11-17T16:16:18.301393 - [0;33m[ReActor][0m - [38;5;173mSTATUS[0m - [0;32mRunning v0.5.1-b2 in ComfyUI[0m2024-11-17T16:16:18.302392 - 
2024-11-17T16:16:18.367366 - Torch version: 2.3.1+cu1212024-11-17T16:16:18.367366 - 
2024-11-17T16:16:18.681780 - (pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider2024-11-17T16:16:18.681780 - 
2024-11-17T16:16:18.681780 - (pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider2024-11-17T16:16:18.681780 - 
2024-11-17T16:16:18.717618 - ------------------------------------------2024-11-17T16:16:18.717618 - 
2024-11-17T16:16:18.717618 - [34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m2024-11-17T16:16:18.717618 - 
2024-11-17T16:16:18.718622 - ------------------------------------------2024-11-17T16:16:18.718622 - 
2024-11-17T16:16:18.718622 - ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md2024-11-17T16:16:18.718622 - 
2024-11-17T16:16:18.718622 - ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki2024-11-17T16:16:18.718622 - 
2024-11-17T16:16:18.718622 - ------------------------------------------2024-11-17T16:16:18.718622 - 
2024-11-17T16:16:18.721623 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2024-11-17T16:16:18.721623 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-11-17T16:16:18.721623 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-11-17T16:16:18.880272 - [34mFizzleDorf Custom Nodes: [92mLoaded[0m2024-11-17T16:16:18.880272 - 
2024-11-17T16:16:19.350143 - All packages from requirements.txt are installed and up to date.2024-11-17T16:16:19.350143 - 
2024-11-17T16:16:19.448616 - llama-cpp installed2024-11-17T16:16:19.449616 - 
2024-11-17T16:16:19.449616 - All packages from requirements.txt are installed and up to date.2024-11-17T16:16:19.449616 - 
2024-11-17T16:16:19.450616 - AutoGPTQ installed2024-11-17T16:16:19.450616 - 
2024-11-17T16:16:19.497270 - [ComfyUI_zfkun] [1;35mcheck start[0m2024-11-17T16:16:19.497270 - 
2024-11-17T16:16:21.002427 - [ComfyUI_zfkun] [93m"Pillow" is not installed. Trying to install.[0m2024-11-17T16:16:21.003428 - 
2024-11-17T16:16:22.508887 - [ComfyUI_zfkun] [92m"Pillow" is installed[0m2024-11-17T16:16:22.509888 - 
2024-11-17T16:16:22.510392 - [ComfyUI_zfkun] [92mall dependency installed[0m2024-11-17T16:16:22.510392 - 
2024-11-17T16:16:22.510392 - [ComfyUI_zfkun] [1;35mcheck end[0m2024-11-17T16:16:22.510392 - 
2024-11-17T16:16:22.512396 - [ComfyUI_zfkun] [1;35mboot start[0m2024-11-17T16:16:22.512396 - 
2024-11-17T16:16:22.514397 - [ComfyUI_zfkun] [92mnode install: preview_text.js[0m2024-11-17T16:16:22.514397 - 
2024-11-17T16:16:22.516491 - [ComfyUI_zfkun] [92mnode install: preview_text_multiline.js[0m2024-11-17T16:16:22.516491 - 
2024-11-17T16:16:22.518741 - [ComfyUI_zfkun] [92mnode install: share_screen.js[0m2024-11-17T16:16:22.518741 - 
2024-11-17T16:16:22.520741 - [ComfyUI_zfkun] [1;35mboot end[0m2024-11-17T16:16:22.520741 - 
2024-11-17T16:16:23.219889 - [36;20m[comfy_mtb] | INFO -> loaded [96m88[0m nodes successfuly[0m
2024-11-17T16:16:23.234443 - 
[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m2024-11-17T16:16:23.235434 - 
2024-11-17T16:16:23.282860 - 
2024-11-17T16:16:23.282860 - [92m[rgthree-comfy] Loaded 42 epic nodes. 🎉[00m2024-11-17T16:16:23.283860 - 
2024-11-17T16:16:23.283860 - 
2024-11-17T16:16:23.292132 - ### Loading: ComfyUI-Impact-Pack (V7.10.7)2024-11-17T16:16:23.292132 - 
2024-11-17T16:16:23.300645 - ### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)2024-11-17T16:16:23.300645 - 
2024-11-17T16:16:23.318420 - [Impact Pack] Wildcards loading done.2024-11-17T16:16:23.318420 - 
2024-11-17T16:16:23.323419 - [92m[tinyterraNodes] [32mLoaded[0m2024-11-17T16:16:23.327425 - 
2024-11-17T16:16:23.411475 - 
Import times for custom nodes:
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\quick-connections
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Image-Selector
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\Cup-ClipBoard
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-NodeAligner
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\image-resize-comfyui
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-BiRefNet-Hugo
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_Noise
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\cg-use-everywhere
2024-11-17T16:16:23.411475 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_VisualStylePrompting
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-ELLA
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_kkTranslator_nodes
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Tripo
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-11-17T16:16:23.412680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\execution-inversion-demo-comfyui
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-animatediff
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_essentials
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-portrait-master
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-BrushNet
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-LogicUtils
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\steerable-motion
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-17T16:16:23.413680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Studio
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-prompt-reader-node
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\rgthree-comfy
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\facerestore_cf
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-11-17T16:16:23.414680 -    0.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-ToonCrafter
2024-11-17T16:16:23.414680 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\comfyui_segment_anything
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyLiterals
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-CUP
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Anyline
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
2024-11-17T16:16:23.415679 -    0.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_VLM_nodes
2024-11-17T16:16:23.415679 -    0.2 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-JNodes
2024-11-17T16:16:23.415679 -    0.2 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-17T16:16:23.415679 -    0.2 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-11-17T16:16:23.415679 -    0.2 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
2024-11-17T16:16:23.415679 -    0.3 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\clipseg.py
2024-11-17T16:16:23.415679 -    0.3 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-11-17T16:16:23.415679 -    0.3 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_omost
2024-11-17T16:16:23.416679 -    0.3 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-reactor-node
2024-11-17T16:16:23.416679 -    0.3 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR
2024-11-17T16:16:23.416679 -    0.7 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\comfy_mtb
2024-11-17T16:16:23.416679 -    1.1 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-CCSR
2024-11-17T16:16:23.416679 -    2.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-ADMotionDirector
2024-11-17T16:16:23.416679 -    3.0 seconds: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_zfkun
2024-11-17T16:16:23.416679 - 
2024-11-17T16:16:23.506801 - Starting server

2024-11-17T16:16:23.508305 - To see the GUI go to: http://127.0.0.1:8188
2024-11-17T16:16:24.364797 - FETCH DATA from: D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-11-17T16:16:24.364797 - 2024-11-17T16:16:24.369306 -  [DONE]2024-11-17T16:16:24.369306 - 
2024-11-17T16:17:05.647541 - got prompt
2024-11-17T16:17:05.655962 - Failed to validate prompt for output 30:
2024-11-17T16:17:05.655962 - * CLIPVisionLoader 21:
2024-11-17T16:17:05.655962 -   - Value not in list: clip_name: 'SD1.5_pytorch_model.bin' not in ['CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors', 'CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors', 'clip-vit-large-patch14.bin', 'clip_vision_g.safetensors', 'image encoder.safetensors', 'pytorch_model.bin']
2024-11-17T16:17:05.655962 - Output will be ignored
2024-11-17T16:17:05.690817 - Failed to validate prompt for output 16:
2024-11-17T16:17:05.690817 - * VHS_LoadVideoPath 40:
2024-11-17T16:17:05.691809 -   - Custom validation failed for node: video - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:05.691809 -   - Custom validation failed for node: force_rate - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:05.691809 -   - Custom validation failed for node: force_size - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:05.691809 -   - Custom validation failed for node: custom_width - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:05.691809 -   - Custom validation failed for node: custom_height - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:05.691809 -   - Custom validation failed for node: frame_load_cap - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:05.692809 -   - Custom validation failed for node: skip_first_frames - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:05.692809 -   - Custom validation failed for node: select_every_nth - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:05.692809 -   - Custom validation failed for node: unique_id - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:05.692809 - * ControlNetLoader 38:
2024-11-17T16:17:05.692809 -   - Value not in list: control_net_name: 'other\control_v1p_sd15_qrcode_monster.safetensors' not in (list of length 55)
2024-11-17T16:17:05.692809 - Output will be ignored
2024-11-17T16:17:05.693808 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-11-17T16:17:15.926569 - got prompt
2024-11-17T16:17:15.951608 - Failed to validate prompt for output 16:
2024-11-17T16:17:15.951608 - * VHS_LoadVideoPath 40:
2024-11-17T16:17:15.951608 -   - Custom validation failed for node: video - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:15.952609 -   - Custom validation failed for node: force_rate - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:15.952609 -   - Custom validation failed for node: force_size - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:15.952609 -   - Custom validation failed for node: custom_width - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:15.952609 -   - Custom validation failed for node: custom_height - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:15.952609 -   - Custom validation failed for node: frame_load_cap - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:15.952609 -   - Custom validation failed for node: skip_first_frames - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:15.952609 -   - Custom validation failed for node: select_every_nth - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:15.952609 -   - Custom validation failed for node: unique_id - Invalid file path: D:\ComfyUI_windows_portable_nvidia\workflows\ipivsMorphImg2vid_v30HyperSDV3Mm\masks\testy 11_1.mp4
2024-11-17T16:17:15.952609 - * ControlNetLoader 38:
2024-11-17T16:17:15.952609 -   - Value not in list: control_net_name: 'other\control_v1p_sd15_qrcode_monster.safetensors' not in (list of length 55)
2024-11-17T16:17:15.952609 - Output will be ignored
2024-11-17T16:17:15.958702 - WARNING: [WinError 3] The system cannot find the path specified: 'D:\\ComfyUI_windows_portable_nvidia\\workflows\\ipivsMorphImg2vid_v30HyperSDV3Mm\\masks\\testy 11_1.mp4'
2024-11-17T16:17:16.252275 - model weight dtype torch.float16, manual cast: None
2024-11-17T16:17:16.311088 - model_type EPS
2024-11-17T16:17:17.065846 - Using xformers attention in VAE
2024-11-17T16:17:17.068355 - Using xformers attention in VAE
2024-11-17T16:17:18.361935 - [33mINFO: Clip Vision model loaded from D:\ComfyUI\ComfyUI_Max\ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors[0m2024-11-17T16:17:18.368446 - 
2024-11-17T16:17:18.582256 - [33mINFO: IPAdapter model loaded from D:\ComfyUI\ComfyUI_Max\ComfyUI\models\ipadapter\ip-adapter-plus_sd15.bin[0m2024-11-17T16:17:18.591033 - 
2024-11-17T16:17:18.615988 - Requested to load SD1ClipModel
2024-11-17T16:17:18.700710 - Loading 1 new model
2024-11-17T16:17:18.845951 - loaded completely 0.0 235.84423828125 True
2024-11-17T16:17:19.434677 - Requested to load CLIPVisionModelProjection
2024-11-17T16:17:19.434677 - Loading 1 new model
2024-11-17T16:17:19.708656 - loaded completely 0.0 1208.09814453125 True
2024-11-17T16:17:27.155371 - Prompt executed in 11.20 seconds
2024-11-17T16:18:02.656441 - got prompt
2024-11-17T16:18:09.381464 - Using xformers attention in VAE
2024-11-17T16:18:09.383476 - Using xformers attention in VAE
2024-11-17T16:18:11.684159 - Requested to load AutoencoderKL
2024-11-17T16:18:11.684159 - Loading 1 new model
2024-11-17T16:18:11.761314 - loaded completely 0.0 159.55708122253418 True
2024-11-17T16:18:13.834642 - !!! Exception during processing !!! ControlNet.__init__() got an unexpected keyword argument 'device'
2024-11-17T16:18:13.836630 - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes_sparsectrl.py", line 45, in load_controlnet
    sparsectrl = load_sparsectrl(sparsectrl_path, timestep_keyframe=tk_optional, sparse_settings=sparse_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 795, in load_sparsectrl
    control = SparseCtrlAdvanced(control_model, timestep_keyframes=timestep_keyframe, sparse_settings=sparse_settings, global_average_pooling=global_average_pooling, load_device=load_device, manual_cast_dtype=manual_cast_dtype)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 315, in __init__
    super().__init__(control_model=control_model, timestep_keyframes=timestep_keyframes, global_average_pooling=global_average_pooling, device=device, load_device=load_device, manual_cast_dtype=manual_cast_dtype)
  File "D:\ComfyUI\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 25, in __init__
    super().__init__(control_model=control_model, global_average_pooling=global_average_pooling, compression_ratio=compression_ratio, latent_format=latent_format, device=device, load_device=load_device, manual_cast_dtype=manual_cast_dtype)
TypeError: ControlNet.__init__() got an unexpected keyword argument 'device'

2024-11-17T16:18:13.839150 - Prompt executed in 11.14 seconds
2024-11-17T16:18:14.218374 - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.

**Comment by Kosinkadink** [comment]
Looking at your traceback, you are not on the latest version of Advanced-ControlNet main branch. Here is what the line that throws that error for you is supposed to look like:
https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/blob/main/adv_control/control.py#L25

Make sure you are on the main branch of Advanced-ControlNet, and that the update did not fail. I am not sure why ComfyUI-Manager messes up updates sometimes, especially since Advanced-ControlNet has no dependencies.
